<a href="https://colab.research.google.com/github/MuhammadMaazKhan/Machine-Learning/blob/main/7.Deep%20Learning/1.ANN/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

by default is the **Adam Optimizer**, which is a very performance optimizer that can perform stochastic gradient descent.
 what stochastic gradient descent allows to do.
 it is what will update the weights in order to reduce the loss error between your predictions
and the real results

**loss function**, which is the way to
compute the difference between the predictions
and the real results.

 if you were **doing non-binary classification.**
You know, like for example
predicting three different categories while here
you would have to enter a category called **cross entropy loss** when doing non-binary classification
**when predicting more than two categories**
while the **activation should not be sigmoid**,
but **soft max**

the list of the different **metrics**
with which you want to evaluate your ANN
during the training, but we will only choose the main one.
You know, the most essential one
which is the **accuracy** and which you have to enter in quotes.

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

the **batch size.**

Because indeed batch learning is always more efficient and
more performance when training an artificial neural network.
Meaning that instead of comparing your prediction
to the real result, one by one, you know
to compute and reduce the loss, well
you are gonna do that with several predictions compared
to several real results into a batchAnd the batch size here, you know the **batch size** parameter gives exactly the **number of predictions** you want to have in the batch to be compared to that same number of real results.

And the classic value
of the batch size that is usually chosen is 32, right?
If you don't want to spend too much time tuning this hyper parameter well I recommend to choose the default value 32.

 a neural network has to be trained
over a certain amount of **epics**
so has to improve the accuracy over time.
So we can just take 100 epics.

your new network needs a certain amount
of epics in order to learn properly, you know
learn the correlations to get the ultimate best predictions.And the final accuracy we get on the training set
we'll have to check the same on the test set
is averaging around 0.86. That means that out of 100 observations you have 86 correct predictions.

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.8037 - accuracy: 0.5185
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5291 - accuracy: 0.7901
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4888 - accuracy: 0.7952
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4668 - accuracy: 0.7979
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4478 - accuracy: 0.7994
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4302 - accuracy: 0.8049
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4123 - accuracy: 0.8119
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3947 - accuracy: 0.8238
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3807 - accuracy: 0.8355
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3720 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

**sc.transform** for standardization which it learn from x-test in feature scaling step

that this customer leaves the bank is 0.04, you know,
And therefore it is predicted that this customer has a very
low chance to leave the bank. **{ get 0.4 by removing > 0.5}**

And if **you don't want** the outcome in the form
of a **probability**, well the trick
You just need to add here, **" > 0.5 "**, why is that?

and then oh 0.5, why is that?
 ANN predict the SC transformed and all the informations
of the customers up to here returns exactly
the predicted probability.

And here we choose a threshold of 0.5
to say that if that predicted probability
is larger than 0.5, well, we will consider the final result to be one, right?

Because the predicted probability
that the outcome is one is larger than 0.5,
meaning that there is more
than 50% chance that the predicted outcome is one.
So we'll consider it to be one.

And however, if the predictive probability
that the customer leaves the bank is below 0.5,
well, we will consider it to be zero.

Of course, **you can choose a different value**
of the threshold, especially when you have critical outcome
you know, for a critical decision,
and in that case, you can, for example,
increase the threshold.

This totally makes sense for our case study.
And therefore, now if we re-execute this sale,
we will of course get the final outcome,
which will be of course, **zero or false**.

 the customer won't leave the bank.

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

**Reshape**

- y_pred.reshape(len(y_pred),1): Converts y_pred into a column vector.
- y_test.reshape(len(y_test),1): Converts y_test into a column vector.

**Concatenation**
- np.concatenate((...), 1): Joins these two column vectors horizontally (along axis 1).
- This results in a 2D array where each row contains [predicted value, actual value].

### Dummy data
y_pred = np.array([0.9, 0.2, 0.7])

y_test = np.array([1, 0, 1])

### outPut

[[0.9  1 ]
 [0.2  0 ]
 [0.7  1 ]]

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 200  205]]


0.8605